server:
  port: 8085
hm:
  db:
    database: hm-trade
  swagger:
    title: 黑马商城交易服务接口文档
    package: com.hmall.trade.controller
feign:
  okhttp:
    enabled: true
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
