server:
  port: 8084
hm:
  db:
    database: hm-user
  swagger:
    title: 黑马商城用户服务接口文档
    package: com.hmall.user.controller
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
feign:
  okhttp:
    enabled: true
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
